/**
 * Fallback sample data for portfolio and gallery
 * Used when PostgreSQL database is not available.
 * In production with a configured POSTGRES_URL, real database data is used instead.
 */

const PLACEHOLDER_BASE = 'https://placehold.co';

const fallbackPortfolio = [
  {
    id: 1,
    title: 'Commercial Office Electrical Installation',
    description: 'Complete electrical fit-out for a modern 5-story commercial office building, including LED lighting systems, power distribution, and smart building controls.',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Commercial+Office`,
    category: 'Commercial',
    client_name: 'TechCorp Ltd.',
    project_date: 'March 2024',
    featured: true,
    display_order: 1,
    created_at: '2024-03-15T10:00:00Z',
  },
  {
    id: 2,
    title: 'Residential Smart Home Wiring',
    description: 'Full wiring and smart home automation for a luxury 4-bedroom residence with home cinema, automated lighting, and security systems.',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Smart+Home`,
    category: 'Residential',
    client_name: 'Private Client',
    project_date: 'January 2024',
    featured: true,
    display_order: 2,
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 3,
    title: 'Industrial Factory Power Setup',
    description: 'High-capacity electrical infrastructure for manufacturing facility with 3-phase power, motor control panels, and backup systems.',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Industrial+Factory`,
    category: 'Industrial',
    client_name: 'Delta Manufacturing',
    project_date: 'November 2023',
    featured: true,
    display_order: 3,
    created_at: '2023-11-10T10:00:00Z',
  },
  {
    id: 4,
    title: 'Retail Store LED Retrofit',
    description: 'Energy-efficient LED lighting retrofit reducing consumption by 60% across 12 store locations.',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Retail+LED+Retrofit`,
    category: 'Commercial',
    client_name: 'Style & Co.',
    project_date: 'September 2023',
    featured: false,
    display_order: 5,
    created_at: '2023-09-05T10:00:00Z',
  },
  {
    id: 5,
    title: 'Restaurant Electrical & Lighting Design',
    description: 'Custom electrical and ambient lighting design for high-end restaurant with dimmable LED and kitchen power solutions.',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Restaurant+Lighting`,
    category: 'Commercial',
    client_name: 'Bistro Lumière',
    project_date: 'August 2023',
    featured: false,
    display_order: 6,
    created_at: '2023-08-12T10:00:00Z',
  },
  {
    id: 6,
    title: 'Warehouse Electrical Maintenance',
    description: 'Comprehensive electrical maintenance and safety inspection for large distribution warehouse.',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Warehouse+Maintenance`,
    category: 'Industrial',
    client_name: 'Global Logistics Inc.',
    project_date: 'July 2023',
    featured: false,
    display_order: 7,
    created_at: '2023-07-18T10:00:00Z',
  },
];

const fallbackGallery = [
  {
    id: 1,
    title: 'Before & After: Office Lighting Upgrade',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Before+%26+After+1`,
    category: 'Projects',
    description: 'Dramatic transformation of office lighting from fluorescent to modern LED.',
    display_order: 1,
    created_at: '2024-03-20T10:00:00Z',
  },
  {
    id: 2,
    title: 'Team Installation Day',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Team+Installation`,
    category: 'Team',
    description: 'Skilled electricians installing conduit systems at a commercial site.',
    display_order: 2,
    created_at: '2024-02-15T10:00:00Z',
  },
  {
    id: 3,
    title: 'High-Bay Industrial Lighting',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=High-Bay+Lighting`,
    category: 'Equipment',
    description: 'Installation of high-bay LED lighting in manufacturing facility.',
    display_order: 3,
    created_at: '2024-01-25T10:00:00Z',
  },
  {
    id: 4,
    title: 'Smart Home Control Panel',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Smart+Control+Panel`,
    category: 'Projects',
    description: 'Custom smart home control panel with automated scenes.',
    display_order: 4,
    created_at: '2023-12-10T10:00:00Z',
  },
  {
    id: 5,
    title: 'Team Safety Briefing',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Safety+Briefing`,
    category: 'Team',
    description: 'Morning safety briefing before commercial installation.',
    display_order: 5,
    created_at: '2023-11-30T10:00:00Z',
  },
  {
    id: 6,
    title: 'Electrical Panel Upgrade',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Panel+Upgrade`,
    category: 'Equipment',
    description: 'Replacing outdated panels with modern code-compliant units.',
    display_order: 6,
    created_at: '2023-10-15T10:00:00Z',
  },
  {
    id: 7,
    title: 'Annual Company Event 2023',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Company+Event`,
    category: 'Events',
    description: 'Team celebration after completing major industrial project.',
    display_order: 7,
    created_at: '2023-10-05T10:00:00Z',
  },
  {
    id: 8,
    title: 'Emergency Repair Response',
    image_url: `${PLACEHOLDER_BASE}/600x400/0F172A/F59E0B?text=Emergency+Repair`,
    category: 'Projects',
    description: '24/7 emergency response to power outage at residential complex.',
    display_order: 8,
    created_at: '2023-09-22T10:00:00Z',
  },
];

module.exports = { fallbackPortfolio, fallbackGallery };